version: "3"

services:
  app:
    image: vfusion_daemon:vfusion_daemon
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - ./vfusion_daemon:/opt
      - app_node_modules:/opt/node_modules
    environment:
      NODE_ENV: development
    network_mode: host
#    networks:
#      main:
#        aliases:
#          - app
  
#  freeswitch:
#    image: freeswitch:vfusion_daemon
#    build:
#      context: .
#      dockerfile: Dockerfile.freeswitch
#    ports: 
#      - "5060:5060/udp"
#    networks:
#      main:
#        aliases: 
#          - fs

#networks:
# main:

volumes:
  app_node_modules:
